# Generated by Django 5.1.5 on 2025-02-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='visitor', max_length=100),
        ),
    ]
